# Generated by Django 5.2.7 on 2025-11-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(blank=True, max_length=64)),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='api.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'recipe_id', 'recipe_name')},
            },
        ),
    ]
